.TH torify 1 "" Jan-2009 ""
.\" manual page by Peter Palfrader and Jacob Appelbaum
.SH NAME
.LP
torify \- wrapper for torsocks or tsocks and tor

.SH SYNOPSIS
\fBtorify\fP\ \fIapplication\fP\ [\fIapplication's\ arguments\fP]

.SH DESCRIPTION
\fBtorify\fR is a simple wrapper that attempts to find the best underlying Tor
wrapper available on a system. It calls torsocks or tsocks with a tor specific
configuration file.

torsocks is an improved wrapper that explictly rejects UDP, safely resolves DNS
lookups and properly socksifies your TCP connections.

tsocks itself is a wrapper between the tsocks library and the application
that you would like to run socksified.

Please note that since both method use LD_PRELOAD, torify cannot be applied
to suid binaries.

.SH WARNING
You should also be aware that the way tsocks currently works only TCP
connections are socksified.  Be aware that this will in most circumstances
not include hostname lookups which would still be routed through your
normal system resolver to your usual resolving nameservers.  The
\fBtor-resolve\fR(1) tool can be useful as a workaround in some cases.
The Tor FAQ at https://wiki.torproject.org/noreply/TheOnionRouter/TorFAQ might
have further information on this subject.

When used with torsocks, torify should not leak DNS requests or UDP data.

Both will leak ICMP data.

.SH SEE ALSO
.BR tor (1),
.BR tor-resolve (1),
.BR torsocks (1),
.BR tsocks (1),
.BR tsocks.conf (5).
