#! /bin/sh
# Wrapper script for use of the tsocks(8) transparent socksification library
# See the tsocks(1) and torify(1) manpages.

TSOCKS_CONF_FILE=/etc/tor/tor-tsocks.conf
export TSOCKS_CONF_FILE
exec tsocks "$@"
