#! /bin/sh -e
## 04_fix_test.dpatch by  <weasel@debian.org>
##
## All lines beginning with `## DP:' are a description of the patch.
## DP: No description.

if [ $# -lt 1 ]; then
    echo "`basename $0`: script expects -patch|-unpatch as argument" >&2
    exit 1
fi

[ -f debian/patches/00patch-opts ] && . debian/patches/00patch-opts
patch_opts="${patch_opts:--f --no-backup-if-mismatch} ${2:+-d $2}"

case "$1" in
    -patch) patch -p1 ${patch_opts} < $0;;
    -unpatch) patch -R -p1 ${patch_opts} < $0;;
    *)
        echo "`basename $0`: script expects -patch|-unpatch as argument" >&2
        exit 1;;
esac

exit 0

@DPATCH@
diff -urNad tor-0.0.9pre4/src/or/test.c /tmp/dpep.hUQG4a/tor-0.0.9pre4/src/or/test.c
--- tor-0.0.9pre4/src/or/test.c	2004-10-17 00:14:52.000000000 +0200
+++ /tmp/dpep.hUQG4a/tor-0.0.9pre4/src/or/test.c	2004-10-17 19:03:33.772660687 +0200
@@ -919,7 +919,8 @@
   test_assert(!is_legal_nickname_or_hexdigest("abcdefghijklmnopqrst"));
 
   get_platform_str(platform, sizeof(platform));
-
+  memset(&r1,0,sizeof(r1));
+  memset(&r2,0,sizeof(r2));
   r1.address = "testaddr1.foo.bar";
   r1.addr = 0xc0a80001u; /* 192.168.0.1 */
   r1.published_on = 0;
