#!/usr/bin/perl

#require 'sys/syscall.ph';
$|=1;

$total = 1;
$target = "http://www.cnn.com/";

for($i=0;$i<$total;$i++) {
  print "Starting client $i\n";
  $pid = fork();
  if(!$pid) {
    open(FD,"wget -q -O - $target|");
    $c = 0;
    while(<FD>) {
      $c += length($_);
    }
#    $TIMEVAL_T = "LL";
#    $now = pack($TIMEVAL_T, ());
#    syscall(&SYS_gettimeofday, $now, 0) != -1 or die "gettimeofday: $!";
#    @now = unpack($TIMEVAL_T, $now);
    print "Client $i exiting ($c chars).\n";
    exit(0);
  }
# sleep(1);
}

