all: csiphash.lib

CFLAGS = /O2 /MT /I ..\win32 /I ..\..\..\build-alpha\include /I ..\common \
    /I ..\ext

CSIPHASH_OBJECTS = csiphash.obj

csiphash.lib: $(CSIPHASH_OBJECTS)
	lib $(CSIPHASH_OBJECTS) $(CURVE25519_DONNA_OBJECTS) /out:csiphash.lib

clean:
	del *.obj *.lib
