[package]
authors = ["The Tor Project"]
name = "tor_util"
version = "0.0.1"

[lib]
name = "tor_util"
path = "lib.rs"

[dependencies.tor_allocate]
path = "../tor_allocate"

[dependencies.tor_log]
path = "../tor_log"

[dependencies]
libc = "=0.2.39"
