#!/bin/sh

##
# Polipo
##

. /etc/rc.common

StartService ()
{
    if [ -f /Library/Polipo/bin/polipo ]; then
        if pid=$(GetPID polipo); then
            return 0
	else if [ "${POLIPO:=-NO-}" = "-YES-" ]; then
	ConsoleMessage "Starting Polipo"
    	/Library/Polipo/bin/polipo -c /Library/Polipo/www/config
	     fi
     	fi
    fi
}

StopService ()
{
    if pid=$(GetPID polipo); then
        ConsoleMessage "Stopping Polipo"
        kill -TERM "${pid}"
    else
        ConsoleMessage "Polipo not responding."
# Just for sanity (sometimes necessary.)
        killall tor 2>/dev/null
    fi
}

RestartService ()
{
  StopService
  StartService
}

RunService "$1"
