#!/bin/sh
# Copyright 2013  The Tor Project, Inc.
# See LICENSE for licensing information.

# cov-diff -- compare two directories full of gcov files.

DIRA="$1"
DIRB="$2"

for A in $DIRA/*; do
  B=$DIRB/`basename $A`
  perl -pe 's/^\s*\d+:/        1:/; s/^([^:]+:)[\d\s]+:/$1/; s/^ *-:(Runs|Programs):.*//;' "$A" > "$A.tmp"
  perl -pe 's/^\s*\d+:/        1:/; s/^([^:]+:)[\d\s]+:/$1/; s/^ *-:(Runs|Programs):.*//;' "$B" > "$B.tmp"
  diff -u "$A.tmp" "$B.tmp"
  rm "$A.tmp" "$B.tmp"
done

