[package]
authors = ["The Tor Project"]
version = "0.0.1"
name = "external"
build = "../build.rs"

[dependencies]
libc = "=0.2.39"
smartlist = { path = "../smartlist" }
tor_allocate = { path = "../tor_allocate" }

[lib]
name = "external"
path = "lib.rs"
